[package]
name = "Rust-Pong"
version = "1.0.1"
authors = ["Vianpyro"]
edition = "2024"

[dependencies]
ggez = "0.9.3"
rand = "0.9.2"
rust-embed = "8.0"

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = "s"
panic = "abort"
strip = true
