[package]
name = "Rust-Pong"
version = "0.1.0"
authors = ["Vianpyro"]
edition = "2024"

[dependencies]
ggez = "0.9.3"
rand = "0.9.2"

[profile.release]
lto = true
panic = "abort"
strip = true
opt-level = "z"
