name: Create Release on PR Merge

on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/**/*.rs'
    #   - 'Cargo.toml'

permissions:
  contents: write

jobs:
  build:
    name: Build Game Binaries
    uses: ./.github/workflows/build-game-binary.yml
    secrets: inherit

  create_release:
    name: Create Release and Upload Assets
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download build artifacts (Linux)
        uses: actions/download-artifact@v4
        with:
          name: Pong-ubuntu-latest
          path: dist/Pong-ubuntu-latest

      - name: Download build artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: Pong-windows-latest
          path: dist/Pong-windows-latest

      - name: Download build artifacts (macOS)
        uses: actions/download-artifact@v4
        with:
          name: Pong-macos-latest
          path: dist/Pong-macos-latest

      - name: Create GitHub release and upload assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}-${{ github.sha }}
          name: "Release #${{ github.run_number }}"
          generate_release_notes: true
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          files: |
            dist/Pong-ubuntu-latest/**/rust-pong
            dist/Pong-ubuntu-latest/**/Rust-Pong
            dist/Pong-macos-latest/**/rust-pong
            dist/Pong-macos-latest/**/Rust-Pong
            dist/Pong-windows-latest/**/rust-pong.exe
            dist/Pong-windows-latest/**/Rust-Pong.exe
